#!/bin/sh
cd -- "$(dirname "$0")/.." || exit 1

message=$(cat "$1")

echo "$message" | grep -E "^\[version\] .+" >/dev/null 2>&1 && exit 0
echo "$message" | grep -E "^(feat|fix|chore|docs|refactor|test|version): .+" >/dev/null 2>&1 && exit 0

echo "❌ Commit message does not follow convention"
exit 1
